services:
  connextion.web:
    image: connextion.web
    build:
      context: .
      dockerfile: src/Connextion.Web/Dockerfile
    ports:
    - "8080:8080"
    restart: always
    
  neo4j:
    image: neo4j:latest
    volumes:
      - /$HOME/neo4j/logs:/logs
      - /$HOME/neo4j/config:/config
      - /$HOME/neo4j/data:/data
      - /$HOME/neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/your_password
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always