services:
  connextion.web:
    image: connextion.web
    depends_on:
      - neo4j
    build:
      context: .
      dockerfile: src/Connextion.Web/Dockerfile
    ports:
      - "8080:8080"
    restart: always
  
  neo4j:
    image: neo4j:latest
    volumes:
      - neo4j-logs:/logs
      - neo4j-config:/config
      - neo4j-data:/data
      - neo4j-plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/neo4j_pass
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
    
volumes:
  neo4j-logs:
  neo4j-config:
  neo4j-data:
  neo4j-plugins: