# This is a generated file. Not intended for manual editing.
services:
  connextion.web:
    build:
      context: "/home/me/Code/Connextion"
      dockerfile: "src/Connextion.Web/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net8.0/Connextion.Web.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "connextion.web:dev"
    ports:
    - "127.0.0.1:57020:57100"
    - "127.0.0.1:57220:57300"
    volumes:
    - "/home/me/.nuget/packages:/home/app/.nuget/packages"
    - "/home/me/Code/Connextion/src/Connextion.Web:/app:rw"
    - "/home/me/Code/Connextion:/src:rw"
    - "/home/me/.local/share/JetBrains/RiderRemoteDebugger/2024.2.5/Linux64:/opt/rider-debugger"
    - "/home/me/.local/share/JetBrains/Toolbox/apps/rider/bin:/etc/opt/rider-debugger/backend-log.xml"
    - "/home/me/.cache/JetBrains/Rider2024.2/log/DebuggerWorker/JetBrains.Debugger.Worker.2024_10_04_16_27_09:/var/opt/rider-debugger:rw"
    working_dir: "/app"
