# This is a generated file. Not intended for manual editing.
services:
  connextion.web:
    build:
      context: "/home/me/Code/Connextion"
      dockerfile: "src/Connextion.Web/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Connextion.Web.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net8.0/Connextion.Web.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "connextion.web:dev"
    ports: []
    volumes:
    - "/home/me/.nuget/packages:/home/app/.nuget/packages"
    - "/home/me/Code/Connextion/src/Connextion.Web:/app:rw"
    - "/home/me/Code/Connextion:/src:rw"
    working_dir: "/app"
